# Generated by Django 5.1.2 on 2024-12-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matrimony", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="father",
        ),
        migrations.AddField(
            model_name="profile",
            name="father_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="FatherProfile",
        ),
    ]
